language: node_js
node_js:
  - 12
script:
  - npm run test:unit
  - test:coverage
  - coverage:show
  - npm run coverage:push

before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)