version: 2.1
jobs:
  build:
    working_directory: ~/VirTuAula-ui
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: npm run test
      - run:
          name: unit
          command: npm run test:unit
      - run:
          name: coverage
          command: npm run test:coverage
      - run:
          name: push
          command: npm run coverage:push
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules